import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components'

const inter = Inter({ subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
  title: 'Next LMS',
  description: 'This is my Next.js LMS site.',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
  )
}
