-- AlterTable
ALTER TABLE "Administrator" ALTER COLUMN "joinedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastLogin" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Assignment" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "dueDate" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Instructor" ALTER COLUMN "bio" DROP NOT NULL,
ALTER COLUMN "department" DROP NOT NULL,
ALTER COLUMN "joinedAt" DROP NOT NULL,
ALTER COLUMN "officeHours" DROP NOT NULL,
ALTER COLUMN "officeLocation" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "enrolledAt" DROP NOT NULL,
ALTER COLUMN "gpa" DROP NOT NULL,
ALTER COLUMN "graduatedAt" DROP NOT NULL,
ALTER COLUMN "major" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Submission" ALTER COLUMN "content" DROP NOT NULL,
ALTER COLUMN "submittedAt" DROP NOT NULL,
ALTER COLUMN "grade" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "dob" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "avatar" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "bio" DROP NOT NULL;
